version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development
    ignore:
      - dependency-name: "eslint"
        versions: [">=10"]
      - dependency-name: "@eslint/js"
        versions: [">=10"]
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      actions:
        patterns:
          - "*"
